FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile --allow-scripts

COPY . .

RUN pnpm build

EXPOSE 8080

CMD ["node", "dist/index.mjs"]
